routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleStatusController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Auth\RegisterController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Auth
    //Login
    Route::get('/login', [LoginController::class, 'index'])->name('admin.login');
    Route::post('/login', [LoginController::class, 'login']);

    //Register
    Route::get('/register', [RegisterController::class, 'index'])->name('admin.register');
    Route::post('/register', [RegisterController::class, 'register']);

    //Logout
    Route::get('/logout', [LoginController::class, 'logout'])->name('admin.logout');

//Dashboard
Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard', [DashboardController::class, 'index']);

    //Users
    Route::resource('/users', '\App\Http\Controllers\Admin\UserController');

    //Articles
    Route::resource('/articles', '\App\Http\Controllers\Admin\ArticleController',["as"=>"admin"]);

    //Comments
    Route::get('/comments/create/{article_id}', [CommentController::class, 'create'])->name('admin.comments.create');
    Route::post('/comments/{article_id}', [CommentController::class, 'store'])->name('admin.comments.store');

    //Edit Profile
    Route::get('/profile/edit', [ProfileController::class, 'edit']);

    //Active Articles
    Route::get('/article/active/{article_id}', [ArticleStatusController::class, 'update'])->name("admin.article.active")->middleware("reviewer");
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('welcome');
Route::get('/index', [HomeController::class, 'index']);

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        "title",
        "content",
        "status",
        "user_id"
    ];

    /**
     * Scope a query to only include active articles.
     */
    public function scopeActive(Builder $query): void
    {
        $query->where('status', 1);
    }

    /**
     * Get the user associated with the article.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo The user relation.
     */
    public function user(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get all the comments associated with the article.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany The comments relation.
     */
    public function comments(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Comment::class);
    }

}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use App\Repository\ArticleRepository;
use App\Services\ArticleService;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(ArticleRepository $articleRepository): View
    {
        // Get all articles and transform them using the ArticleResource
        $articles = $articleRepository->searchFromRequest(request());
        $title = trans('admin.articles');

        // Pass the articles and title to the view
        return view("admin.article.index", compact("articles", "title"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create(): View
    {
        // Initialize article and title variables
        $article = null;
        $title = trans('admin.add article');

        // Pass the article and title to the view
        return view("admin.article.form", compact("article", "title"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\ArticleRequest  $request
     * @param  \App\Services\ArticleService  $articleService
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ArticleRequest $request, ArticleService $articleService): RedirectResponse
    {
        // Create a new article using the validated data
        $articleService->execute($request->validated());

        // Flash a success message to the session
        session()->flash('success', trans("admin.add Successfully"));

        // Redirect the user to the create form again
        return redirect()->route('admin.articles.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\View\View
     */
    public function edit(Article $article): View
    {
        // Set the title for the edit form
        $title = trans('admin.edit article');

        // Pass the article and title to the view
        return view("admin.article.form", compact("article", "title"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Models\Article  $article
     * @param  \App\Http\Requests\ArticleRequest  $request
     * @param  \App\Services\ArticleService  $articleService
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Article $article, ArticleRequest $request, ArticleService $articleService): RedirectResponse
    {
        // Update the article with the validated data
        $articleService->execute($request->validated(), $article);

        // Flash a success message to the session
        session()->flash('success', trans("admin.edit Successfully"));

        // Redirect the user back to the previous page
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @param  \App\Services\ArticleService  $articleService
     * @return void
     */
    public function destroy(int $id, ArticleService $articleService)
    {
        // Delete the article using the ArticleService
        return $articleService->delete($id);
    }
}

resources/views/admin/article/form.blade.php
@extends('admin.layouts.app')

@section('content')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>
            <div class="row breadcrumbs-top d-inline-block">
                <div class="breadcrumb-wrapper col-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ aurl("/articles") }}">{{ trans("admin.articles") }}</a>
                        </li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <!-- Striped row layout section start -->
        <section id="striped-row-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" id="horz-layout-icons">{{ $title }}</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collpase show">
                            <div class="card-body">
                                @if ($article)
                                    <form class="form form-horizontal striped-rows form-bordered" method="post"  action="{{ route('admin.articles.update', [$article->id]) }}">
                                    @csrf
                                    @method('PATCH')
                                @else
                                    <form class="form form-horizontal striped-rows form-bordered" method="post"  action="{{ route('admin.articles.store') }}">
                                    @csrf
                                @endif
                                    <div class="form-body">

                                        <div class="form-group row">
                                            <label class="col-md-3 label-control" for="timesheetinput2">{{ trans("validation.attributes.title") }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <input type="text" required  class="form-control" placeholder="{{ trans("validation.attributes.title") }}"
                                                    name="title" value="{{ $article ? $article->title : old('title') }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-md-3 label-control" for="timesheetinput2">{{ trans("validation.attributes.content") }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <textarea id="content" name="content" rows="4" class="form-control">{{ $article ? $article->content : old('content') }}</textarea>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-md-3 label-control" for="timesheetinput2">{{ trans('validation.attributes.status') }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <select name="status" class="form-control">
                                                        <option value="1" {{ $article?->status == 1 ? "selected" : ""   }}>{{ trans("admin.active") }}</option>
                                                        <option value="0" {{ $article?->status == 0 ? "selected" : ""   }}>{{ trans("admin.inactive") }}</option>
                                                    </select>
                                                    <div class="form-control-position">
                                                        <i class="la la-reorder"></i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="form-actions right">
                                        <button type="submit" class="btn btn-primary">
                                            <i class="la la-check-square-o"></i> {{ trans("admin.save") }}
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/admin/article/index.blade.php
@extends('admin.layouts.app')


@section('content')
    <div class="content-header row">
      <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>
        <div class="row breadcrumbs-top d-inline-block">
          <div class="breadcrumb-wrapper col-12">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ aurl("/articles/create") }}">{{ trans('admin.add article') }}</a>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <div class="content-body">
      <!-- HTML5 export buttons table -->
      <!-- Column selectors table -->
      <section id="column-selectors">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">{{ $title }}</h4>
                <form id="search" method="get" >
                  <br />
                  <div class="container">
                    <div class="row">
                      <div class="col-md-2">
                        <label for="title">{{ trans('validation.attributes.title') }}</label>
                        <input type="text" id="title" placeholder="{{ trans('validation.attributes.title') }}" value="{{ request()->input('filter.title') ?? '' }}" class="form-control" style="display:inline;" name="filter[title]" />                  
                      </div>
                      <div class="col-md-3">
                        <label for="content">{{ trans('validation.attributes.content') }}</label>
                        <input type="text" id="content" placeholder="{{ trans('validation.attributes.content') }}" value="{{ request()->input('filter.content') ?? '' }}" class="form-control" style="display:inline;" name="filter[content]" />                  
                      </div>
                      <div class="col-md-2">
                        <label for="roles">{{ trans('admin.status') }}</label>
                        <select name="filter[status]" class="form-control" id="roles">
                          <option value="" {{ request()->input('filter.status') === null ? "selected" : ""  }}>{{ trans('admin.choose') }}</option>
                          <option value="1" {{ request()->input('filter.status') == 1 ? "selected" : ""  }}>{{ trans("admin.active") }}</option>
                          <option value="0" {{ request()->input('filter.status') === '0' ? "selected" : ""  }}>{{ trans("admin.inactive") }}</option>
                        </select>
                      </div>
                      <div class="col-md-2">
                        <button class="btn btn-success btn-min-width mr-1 mb-1" type="submit" style="display:inline; margin:25px auto;">{{ trans('admin.search') }}</button>
                      </div>
                      <div class="col-md-2">
                        <br>
                        <a class="btn btn-success btn-min-width mr-1 mb-1" href="{{ route("admin.articles.index") }}" style="display:block; margin:3px;">{{ trans('admin.reset_search') }}</a>
                      </div>
                    </div>
                  </div>
                </form>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                <div class="heading-elements">
                  <ul class="list-inline mb-0">
                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                  </ul>
                </div>
              </div>
              <div class="card-content collapse show">
                <div class="card-body card-dashboard">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>{{ trans('validation.attributes.title') }}</th>
                        <th>{{ trans('validation.attributes.status') }}</th>
                        <th>{{ trans('admin.user') }}</th>
                        <th>{{ trans('admin.created_at') }}</th>
                        <th>{{ trans('admin.actions') }}</th>
                        @if (auth()->user()->role_id == 2)
                          <th>{{ trans("admin.active") }}</th>
                        @endif

                      </tr>
                    </thead>
                    <tbody>
                        @foreach ($articles as $article)
                            <tr id="show_{{ $article->id }}">
                                <td>{{ $article->title }}</td>
                                <td>
                                  @if ($article->status == 0)
                                      <span class="text-danger font-weight-bold">{{ trans("admin.inactive") }}</span>
                                  @else
                                      <span class="text-success font-weight-bold">{{ trans("admin.active") }}</span>
                                  @endif
                                </td>
                                <td>{{ $article->user?->name }}</td>
                                <td>{{ $article->created_at ? date("Y-m-d H:i", strtotime($article->created_at)) : "" }}</td>
                                <td>
                                  <a href="{{ aurl('/comments/create/'.$article->id) }}" class="btn btn-primary btn-min-width mr-1 mb-1"><i
                                        class="ft-comment"></i> {{ trans('admin.add_comment') }}</a>
                                    <a href="{{ aurl('/articles/'.$article->id."/edit") }}" class="btn btn-secondary btn-min-width mr-1 mb-1"><i
                                        class="ft-edit"></i> {{ trans('admin.edit') }}</a>
                                    <input type="hidden" value="{{ csrf_token() }}" id="csrf_token" />
                                    <button class="btn btn-danger btn-min-width btn-glow mr-1 mb-1" onclick="DeleteRow({{$article->id}})"><i
                                            class="ft-delete"></i> {{ trans('admin.delete') }}</button>
                                </td>
                                @if (auth()->user()->role_id == 2 && $article->status == 0)
                                  <td><a href="{{ route('admin.article.active', ['article_id' => $article->id]) }}" class="btn btn-success">{{ trans("admin.active") }}</a></td>
                                @endif
                            </tr>
                        @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

          <div class="clearfix"></div>
          <div class="pagination" style="margin:10px auto">
            {{ $articles->appends(request()->except('page'))->render('vendor.pagination.bootstrap-4') }}
          </div>

        </div>
      </section>
      <!--/ Column selectors table -->
</div>


@endsection
@section('scripts')
<script>
  function DeleteRow(id) {
    	           event.preventDefault();
                   swal({
           		    title: "Are you sure?",
           		    text: "You will not be able to recover this imaginary file!",
           		    icon: "warning",
           		    buttons: {
                           cancel: {
                               text: "No, cancel",
                               value: null,
                               visible: true,
                               className: "",
                               closeModal: false,
                           },
                           confirm: {
                               text: "Yes, delete it!",
                               value: true,
                               visible: true,
                               className: "",
                               closeModal: false
                           }
           		    }
           		})
           		.then((isConfirm) => {
           		    if (isConfirm) {
                        $.ajax({
                            type: 'delete',
                             url: "{{aurl("/articles/")}}"+'/'+id,
                            data: {
                                '_token': $('#csrf_token').val(),
                            },

                        });
                        $('#show_' + id).remove();
           		        swal("Deleted!", "Your data has been deleted.", "success");
           		    } else {
           		        swal("Cancelled", "Your data is safe", "error");
           		    }
           		});

            }

</script>
@endsection