routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticleStatusController;
use App\Http\Controllers\Admin\Auth\LoginController;
use App\Http\Controllers\Admin\Auth\RegisterController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

//Auth
    //Login
    Route::get('/login', [LoginController::class, 'index'])->name('admin.login');
    Route::post('/login', [LoginController::class, 'login']);

    //Register
    Route::get('/register', [RegisterController::class, 'index'])->name('admin.register');
    Route::post('/register', [RegisterController::class, 'register']);

    //Logout
    Route::get('/logout', [LoginController::class, 'logout'])->name('admin.logout');

//Dashboard
Route::middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard', [DashboardController::class, 'index']);

    //Users
    Route::resource('/users', '\App\Http\Controllers\Admin\UserController');

    //Articles
    Route::resource('/articles', '\App\Http\Controllers\Admin\ArticleController',["as"=>"admin"]);

    //Comments
    Route::get('/comments/create/{article_id}', [CommentController::class, 'create'])->name('admin.comments.create');
    Route::post('/comments/{article_id}', [CommentController::class, 'store'])->name('admin.comments.store');

    //Edit Profile
    Route::get('/profile/edit', [ProfileController::class, 'edit']);

    //Active Articles
    Route::get('/article/active/{article_id}', [ArticleStatusController::class, 'update'])->name("admin.article.active")->middleware("reviewer");
});

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('welcome');
Route::get('/index', [HomeController::class, 'index']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * Get the list of role with their translations.
     *
     * @param int|null $role The role key.
     * @param bool $admin to show admin or no.
     * 
     * @return array|string The list of role or the translation of a specific role.
     */
    public static function getListRoles(int $role = null, $admin = true)
    {
        if ($admin) {
            $items = [
                1 => trans("permission.admin"),
                2 => trans("permission.reviewer"),
                3 => trans("permission.user"),
            ];
        } else {
            $items = [
                2 => trans("permission.reviewer"),
                3 => trans("permission.user")
            ];
        }

        if (isset($items[$role])) {
            return $items[$role];
        } else {
            return $items;
        }
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use App\Repository\UserRepository;
use App\Services\UserService;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * Display a list of users.
     *
     * @param UserRepository $userRepository The user repository.
     * @return View The view displaying the list of users.
     */
    public function index(UserRepository $userRepository): View
    {
        // Retrieve users based on search criteria
        $users = $userRepository->searchFromRequest(request());
        $title = trans('admin.users');
        
        // Pass users and title to the view
        return view("admin.user.index", compact("users", "title"));
    }

    /**
     * Display the form for creating a new user.
     *
     * @return View The view displaying the user creation form.
     */
    public function create(): View
    {
        $user = null;
        $title = trans('admin.add user');
        
        // Pass user and title to the view
        return view("admin.user.form", compact("user", "title"));
    }

    /**
     * Store a newly created user in the database.
     *
     * @param UserStoreRequest $request The request containing the user data.
     * @param UserService $userService The user service.
     * @return RedirectResponse A redirect response to the user creation form.
     */
    public function store(UserStoreRequest $request, UserService $userService): RedirectResponse
    {
        // Execute the user creation logic
        $userService->execute($request->validated());
        
        // Flash a success message to the session
        session()->flash('success', trans("admin.add Successfully"));
        
        // Redirect to the create user form
        return redirect()->route('users.create');
    }

    /**
     * Display the form for editing an existing user.
     *
     * @param User $user The user to be edited.
     * @return View The view displaying the user edit form.
     */
    public function edit(User $user): View
    {
        $title = trans('admin.edit user');
        
        // Pass user and title to the view
        return view("admin.user.form", compact("user", "title"));
    }

    /**
     * Update the specified user in the database.
     *
     * @param User $user The user to be updated.
     * @param UserUpdateRequest $request The request containing the updated user data.
     * @param UserService $userService The user service.
     * @return RedirectResponse A redirect response back to the previous page.
     */
    public function update(User $user, UserUpdateRequest $request, UserService $userService): RedirectResponse
    {
        // Execute the user update logic
        $userService->execute($request->validated(), $user);
        
        // Flash a success message to the session
        session()->flash('success', trans("admin.edit Successfully"));
        
        // Redirect back to the previous page
        return redirect()->back();
    }

    /**
     * Remove the specified user from the database.
     *
     * @param int $id The ID of the user to be deleted.
     * @param UserService $userService The user service.
     * @return mixed The result of the user deletion operation.
     */
    public function destroy(int $id, UserService $userService)
    {
        // Delete the user
        return $userService->delete($id);
    }
}

resources/views/admin/user/form.blade.php
@extends('admin.layouts.app')

@section('content')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
            <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>
        </div>
    </div>
    <div class="content-body">
        <!-- Striped row layout section start -->
        <section id="striped-row-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title" id="horz-layout-icons">{{ $title }}</h4>
                            <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                            <div class="heading-elements">
                                <ul class="list-inline mb-0">
                                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-content collpase show">
                            <div class="card-body">
                                @if ($user)
                                    <form class="form form-horizontal striped-rows form-bordered" method="post"  action="{{ route('users.update', [$user->id]) }}">
                                    @csrf
                                    @method('PATCH')
                                @else
                                    <form class="form form-horizontal striped-rows form-bordered" method="post"  action="{{ route('users.store') }}">
                                    @csrf
                                @endif
                                    <div class="form-body">

                                        <div class="form-group row">
                                            <label class="col-md-3 label-control" for="timesheetinput2">{{ trans("validation.attributes.name") }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <input type="text" required  class="form-control" placeholder="{{ trans("validation.attributes.name") }}"
                                                    name="name" value="{{ $user ? $user->name : old('name') }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-md-3 label-control" for="timesheetinput2">{{ trans("validation.attributes.email") }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <input type="email" required  class="form-control" placeholder="{{ trans("validation.attributes.email") }}"
                                                    name="email" value="{{ $user ? $user->email : old('email') }}">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-md-3 label-control" for="timesheetinput2">{{ trans("validation.attributes.password") }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <input type="password"  class="form-control" placeholder="{{ trans("validation.attributes.password") }}"
                                                    name="password" value="">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-md-3 label-control" for="timesheetinput2">{{ trans('validation.attributes.roles') }}</label>
                                            <div class="col-md-9">
                                                <div class="position-relative has-icon-left">
                                                    <select name="role_id" class="form-control">
                                                        <option value="1" {{ $user?->role_id == 1 ? "selected" : ""   }}>{{ trans("permission.admin") }}</option>
                                                        <option value="2" {{ $user?->role_id == 2 ? "selected" : ""   }}>{{ trans("permission.reviewer") }}</option>
                                                        <option value="3" {{ $user?->role_id == 3 ? "selected" : ""   }}>{{ trans("permission.user") }}</option>
                                                    </select>
                                                    <div class="form-control-position">
                                                        <i class="la la-reorder"></i>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="form-actions right">
                                        <button type="submit" class="btn btn-primary">
                                            <i class="la la-check-square-o"></i> {{ trans("admin.save") }}
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')


@section('content')
    <div class="content-header row">
      <div class="content-header-left col-md-6 col-12 mb-2 breadcrumb-new">
        <h3 class="content-header-title mb-0 d-inline-block">{{ $title }}</h3>
        <div class="row breadcrumbs-top d-inline-block">
          <div class="breadcrumb-wrapper col-12">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{{ aurl("/users/create") }}">{{ trans('admin.add user') }}</a>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <div class="content-body">
      <!-- HTML5 export buttons table -->
      <!-- Column selectors table -->
      <section id="column-selectors">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">{{ $title }}</h4>
                <form id="search" method="get" >
                  <br />
                  <div class="container">
                    <div class="row">
                      <div class="col-md-2">
                        <label for="name">{{ trans('validation.attributes.name') }}</label>
                        <input type="text" id="name" placeholder="{{ trans('validation.attributes.name') }}" value="{{ request()->input('filter.name') ?? '' }}" class="form-control" style="display:inline;" name="filter[name]" />                  
                      </div>
                      <div class="col-md-2">
                        <label for="email">{{ trans('validation.attributes.email') }}</label>
                        <input type="text" id="email" placeholder="{{ trans('validation.attributes.email') }}"  value="{{ request()->input('filter.email') ?? '' }}" class="form-control" style="display:inline;" name="filter[email]" />
                      </div>
                      <div class="col-md-2">
                        <label for="roles">{{ trans('admin.roles') }}</label>
                        <select name="filter[role_id]" class="form-control" id="roles">
                          <option value="">{{ trans('admin.choose') }}</option>
                          <option value="1" {{ request()->input('filter.role_id') == 1 ? "selected" : ""   }}>{{ trans("permission.admin") }}</option>
                          <option value="2" {{ request()->input('filter.role_id') == 2 ? "selected" : ""   }}>{{ trans("permission.reviewer") }}</option>
                          <option value="3" {{ request()->input('filter.role_id') == 3 ? "selected" : ""   }}>{{ trans("permission.user") }}</option>
                        </select>
                      </div>
                      <div class="col-md-2">
                        <button class="btn btn-success btn-min-width mr-1 mb-1" type="submit" style="display:inline; margin:25px auto;">{{ trans('admin.search') }}</button>
                      </div>
                      <div class="col-md-2">
                        <br>
                        <a class="btn btn-success btn-min-width mr-1 mb-1" href="{{ route("users.index") }}" style="display:block; margin:3px;">{{ trans('admin.reset_search') }}</a>
                      </div>
                    </div>
                  </div>
                </form>
                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                <div class="heading-elements">
                  <ul class="list-inline mb-0">
                    <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                    <li><a data-action="reload"><i class="ft-rotate-cw"></i></a></li>
                    <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                    <li><a data-action="close"><i class="ft-x"></i></a></li>
                  </ul>
                </div>
              </div>
              <div class="card-content collapse show">
                <div class="card-body card-dashboard">
                  {{-- <table class="table table-striped table-bordered dataex-html5-selectors"> --}}
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>{{ trans('validation.attributes.name') }}</th>
                        <th>{{ trans('validation.attributes.email') }}</th>
                        <th>{{ trans('admin.roles') }}</th>
                        <th>{{ trans('admin.created_at') }}</th>
                        <th>{{ trans('admin.actions') }}</th>

                      </tr>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr id="show_{{ $user->id }}">
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ \App\Models\User::getListRoles($user->role_id) }}</td>
                                <td>{{ $user->created_at ? date("Y-m-d H:i", strtotime($user->created_at)) : "" }}</td>
                                <td>
                                  @if ($user->role_id != 4)
                                  <a href="{{ aurl('/users/'.$user->id."/edit") }}" class="btn btn-secondary btn-min-width mr-1 mb-1"><i
                                      class="ft-edit"></i> {{ trans('admin.edit') }}</a>
                                  @endif
                                    <input type="hidden" value="{{ csrf_token() }}" id="csrf_token" />
                                    <button class="btn btn-danger btn-min-width btn-glow mr-1 mb-1" onclick="DeleteRow({{$user->id}})"><i
                                            class="ft-delete"></i> {{ trans('admin.delete') }}</button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

          <div class="clearfix"></div>
          <div class="pagination" style="margin:10px auto">
            {{ $users->appends(request()->except('page'))->render('vendor.pagination.bootstrap-4') }}
          </div>

        </div>
      </section>
      <!--/ Column selectors table -->
</div>


@endsection
@section('scripts')
<script>
  function DeleteRow(id) {
    	           event.preventDefault();
                   swal({
           		    title: "Are you sure?",
           		    text: "You will not be able to recover this imaginary file!",
           		    icon: "warning",
           		    buttons: {
                           cancel: {
                               text: "No, cancel",
                               value: null,
                               visible: true,
                               className: "",
                               closeModal: false,
                           },
                           confirm: {
                               text: "Yes, delete it!",
                               value: true,
                               visible: true,
                               className: "",
                               closeModal: false
                           }
           		    }
           		})
           		.then((isConfirm) => {
           		    if (isConfirm) {
                        $.ajax({
                            type: 'delete',
                             url: "{{aurl("/users/")}}"+'/'+id,
                            data: {
                                '_token': $('#csrf_token').val(),
                            },

                        });
                        $('#show_' + id).remove();
           		        swal("Deleted!", "Your data has been deleted.", "success");
           		    } else {
           		        swal("Cancelled", "Your data is safe", "error");
           		    }
           		});

            }

</script>
@endsection